alias ll='ls -FGlahs'
alias ls='ls -G'
alias ip='dig +short myip.opendns.com @resolver1.opendns.com '
alias lip="ipconfig getifaddr en0"
alias key="cat ~/.ssh/id_rsa.pub | pbcopy; echo 'SSH key copied to clipboard!'"
alias reload="source ~/.bash_profile"
alias mysql-start="mysql.server start"
alias mysql-stop="mysql.server stop"
alias mysql-restart="mysql.server restart"
alias postgres="postgres -D /usr/local/var/postgres"
alias redis="redis-server /usr/local/etc/redis.conf"
alias youse="cd ~/projects/work/webapp"
alias webapp="cd ~/projects/work/webapp"
alias gis="cd ~/projects/work/gis"
alias pricing="cd ~/projects/work/pricing-engine"
alias notifier="cd ~/projects/work/notifier"
alias youse-assist="cd ~/projects/work/youse-assist"
alias arenah="cd ~/projects/private/arenah-rails"
alias rabbit='brew services start rabbitmq'
alias kill-ruby="ps aux | pgrep -lf 'spring|rails|ruby|puma|sneakers' | awk '{print $1}' | xargs kill -9"
alias jmeter="/usr/local/bin/jmeter"
alias memcache="/usr/local/opt/memcached/bin/memcached"
alias jupyter="jupyter notebook"
alias python-server="python -m http.server 8000"
